gestion/gestion/urls.py
from django.urls import include, path
from django.contrib import admin
from gestion import settings
from django.views.static import serve
from inicio import views
from django.conf.urls import handler404, handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'inicio.views.pag_404_not_found'
handler500 = 'inicio.views.pag_500_error_server'

gestion/ra/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import RACreateView, RAUpdateView
from .views import RAListView

app_name = 'resultadoaprendizaje'

urlpatterns = [

	path('resultadoaprendizaje/crear/(<int:pk>)', RACreateView.as_view(), name='crear'),
	path('resultadoaprendizaje/listar/', RAListView.as_view(), name='listar'),
	path('resultadoaprendizaje/actualizar/<int:pk>', RAUpdateView.as_view(), name='actualizar'),
]

gestion/usuario/urls.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import path
from .forms import DocenteCreateView, EstudianteCreateView, DocenteUpdateView, EstudianteUpdateView
from .views import DocenteListView, EstudianteListView

app_name = 'usuario'

urlpatterns = [

	path('usuario/docente/crear/', DocenteCreateView.as_view(), name='crear-docente'),
	path('usuario/estudiante/crear/', EstudianteCreateView.as_view(), name='crear-estudiante'),
	path('usuario/docente/listar/', DocenteListView.as_view(), name='listar-docentes'),
	path('usuario/estudiante/listar/', EstudianteListView.as_view(), name='listar-estudiantes'),
	path('usuario/docente/actualizar/<int:epk>', DocenteUpdateView.as_view(), name='actualizar-docente'),
	path('usuario/estudiante/actualizar/<int:epk>', EstudianteUpdateView.as_view(), name='actualizar-estudiante'),
]

gestion/usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Adjust
from django.core.validators import EmailValidator
from facultad.models import Facultad
from unidadacademica.models import UnidadAcademica
from programa.models import Programa


tipo_estado = (
	(True, 'Activo'),
	(False, 'Inactivo'),
)

#Django por defecto, cuando los modelos no tienen primary_key, coloca una llamada "id"
"""Model: Define la estructura de la tabla Usuario en base de datos"""
class Usuario(models.Model):
	"""Permite definir un listado de Usuarios"""

	#Login o user de la persona
	user = models.OneToOneField(User, default=None, null=True, on_delete=models.CASCADE, db_index=True)
	#Indentificación de la persona, debe ser única
	identificacion = models.CharField(max_length=20, unique=True, help_text="Indentificacion de la persona, debe ser unica")
	#Estado de la persona, activo/inactivo
	estado = models.BooleanField(choices=tipo_estado)
	#Imagen o foto de perfil de la persona
	imagen = models.ImageField(upload_to = "imagenes/persona", blank=True)
	#Thumbnail, que permite reducir la imagen del usuario
	thumbnail = ImageSpecField(source='imagen',
									  processors=[ResizeToFill(100, 50)],
									  format='JPEG',
									  options={'quality': 60})

	"""Permite ordenar la lista de usuarios por user y asignarle el nombre en 
	plural"""
	class Meta:
		abstract = True
		ordering = ['user']
		verbose_name_plural = "Usuarios"

	#Permite determinar una representación en string del objeto Usuario
	def __str__(self):
		return self.user.first_name + " " + self.user.last_name

	"""Permite determinar una representación en string para el objeto Usuario (Para 
	versiones de Python 2)"""
	def __unicode__(self):
		return self.user.first_name + " " + self.user.last_name


#Tipo de cargo adicional docente
DECANO = 'Decano'
VICEDECANO = 'Vicedecano'
ADMINISTRATIVO = 'Administrativo'
DIRECTORPROGRAMA = 'Director de Programa'
DIRECTORESCUELA = 'Director de Escuela'
NINGUNO = 'Ninguno'

tipo_cargo_adicional = (
	(DIRECTORPROGRAMA, 'Director de Programa'),
	(DIRECTORESCUELA, 'Director de Escuela'),
	(NINGUNO, 'Ninguno'),
	(DECANO, 'Decano'),
	(VICEDECANO, 'Vicedecano'),
	(ADMINISTRATIVO, 'Administrativo'),
)

"""Model: Define la estructura de la tabla Profesor que hereda de la tabla Usuario"""
class Profesor(Usuario):
	#Cargo administrativo
	cargoAdministrativo = models.CharField(max_length=50, choices=tipo_cargo_adicional, default=NINGUNO, verbose_name= ('Cargo Administrativo'))
	#Facultad a la que pertenece
	facultad = models.ForeignKey(Facultad,  on_delete=models.CASCADE)
	#Unidad academica a la que pertenece
	unidadAcademica = models.ForeignKey(UnidadAcademica, on_delete=models.CASCADE, verbose_name= ('Unidad Académica'))
	#Programa
	programa = models.ForeignKey(Programa, on_delete=models.CASCADE, null=True, blank=True)

	"""Permite ordenar la lista de profesores por unidad academica y asignarle el nombre en 
	plural"""
	class Meta:
		ordering = ['cargoAdministrativo']
		verbose_name_plural = "Docentes"

	#Permite determinar una representación en string del objeto Profesro
	def __str__(self):
		return self.user.first_name +" "+ self.user.last_name

	"""Permite determinar una representación en string para el objeto Profesor (Para 
	versiones de Python 2)"""
	def __unicode__(self):
		return self.user.first_name +" "+ self.user.last_name


"""Model: Define la estructura de la tabla Profesor que hereda de la tabla Usuario"""
class Estudiante(Usuario):
	#Codigo del estudiante
	codigo = models.PositiveIntegerField()
	#Programas academicos a los que pertenece
	programa = models.ForeignKey(Programa, on_delete=models.CASCADE)

	"""Permite ordenar la lista de profesores por unidad academica y asignarle el nombre en 
	plural"""
	class Meta:
		ordering = ['codigo']
		verbose_name_plural = "Estudiantes"

	#Permite determinar una representación en string del objeto Profesro
	def __str__(self):
		return str(self.codigo)

	"""Permite determinar una representación en string para el objeto Profesor (Para 
	versiones de Python 2)"""
	def __unicode__(self):
		return str(self.codigo)
		

gestion/usuario/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Usuario, Profesor, Estudiante
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate,login
from inicio.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core import validators
from django.core.validators import EmailValidator
from django.views.generic import TemplateView, CreateView
from django.urls import reverse, reverse_lazy



#FormView
class UserForm(LoginRequiredMixin, UserCreationForm):
	"""Permite crear un formulario con los campos del user"""

	username = forms.CharField(label='Nombre de Usuario')
	email = forms.EmailField(label='Correo Electrónico')
	first_name = forms.CharField(label='Nombres' )
	last_name = forms.CharField(label='Apellidos')
	password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput)

	class Meta:
		"""Permite determinar el modelo User y los campos username, email, first_name,
			last_name que se muestran en el formulario Usuario"""
		model = User
		fields = ( "username", "email", "first_name", "last_name")	

#FormView
class ProfesorForm(LoginRequiredMixin, forms.ModelForm):

	class Meta:
		"""Permite determinar el modelo Usuario y los campos identificacion y tipo 
		que se muestran en el formulario"""

		model = Profesor
		fields = ['identificacion', 'imagen', 'estado', 'cargoAdministrativo', 'facultad', 'unidadAcademica', 'programa']


#FormView
class EstudianteForm(LoginRequiredMixin, forms.ModelForm):
	"""Permite mostrar un formulario con la información de Directivo"""

	class Meta:
		"""Permite determinar el modelo Usuario y los campos identificacion y tipo 
		que se muestran en el formulario"""

		model = Estudiante
		fields = ['identificacion', 'imagen', 'estado', 'codigo', 'programa']



"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay 
errores muestra mensajes de error y si no, guarda el objeto"""	
class DocenteCreateView(LoginRequiredMixin, TemplateView):
	"""Permite mostrar el formulario para crear un usuario"""
	model = Profesor
	template_name = 'usuario/docente_form.html'
	form_class = ProfesorForm
	success_url = reverse_lazy('usuario:listar-docentes')


	def get(self,request,*args,**kwargs):
		"""Permite desplegar el formulario de creación de usuario y personal para un 
		peaje"""
		user_form = UserForm()
		docente_form = ProfesorForm()

		forms = [user_form, docente_form]
		context = {
		'section_title':'Crear Usuario Tipo Docente',
		'user_form':user_form,
		'docente_form':docente_form }

		return render(request, 'usuario/docente_form.html', context)


	def post(self,request,*args,**kwargs):
		"""Permite enviar el formulario con la información del usuario, si es valido 
		guarda los datos de lo contrario redirecciona a la lista de usuarios"""

		user_form = UserForm(request.POST)
		docente_form = ProfesorForm(request.POST,request.FILES)

		if user_form.is_valid() and docente_form.is_valid():
			new_user = user_form.save()
			new_persona = docente_form.save(commit=False)
			new_persona.user = new_user
			new_persona.save()
			messages.info(request,'Nuevo usuario tipo docente creado con exito')
			url = reverse('facultad:listar')

			return HttpResponseRedirect(url)

		user_form = UserForm(request.POST)
		docente_form = ProfesorForm(request.POST)
		messages.error(request,'Hay errores en algun campo, revise el formulario')

		context = {
		'section_title':'Crear Usuario Tipo Docente',
		'user_form':user_form,
		'docente_form': docente_form, }

		return render(request, 'usuario/docente_form.html', context)

"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay 
errores muestra mensajes de error y si no, guarda el objeto"""	
class EstudianteCreateView(LoginRequiredMixin, TemplateView):
	"""Permite mostrar el formulario para crear un usuario"""

	def get(self,request,*args,**kwargs):
		"""Permite desplegar el formulario de creación de usuario y personal para un 
		peaje"""
		user_form = UserForm()
		estudiante_form = EstudianteForm()

		forms = [user_form, estudiante_form]
		context = {
		'section_title':'Crear Usuario Tipo Estudiante',
		'user_form':user_form,
		'estudiante_form':estudiante_form }

		return render(request, 'usuario/estudiante_form.html', context)


	def post(self,request,*args,**kwargs):
		"""Permite enviar el formulario con la información del usuario, si es valido 
		guarda los datos de lo contrario redirecciona a la lista de usuarios"""

		user_form = UserForm(request.POST)
		estudiante_form = EstudianteForm(request.POST,request.FILES)

		if user_form.is_valid() and estudiante_form.is_valid():
			new_user = user_form.save()
			new_persona = estudiante_form.save(commit=False)
			new_persona.user = new_user
			new_persona.save()

			messages.info(request,'Nuevo usuario tipo estudiante creado con exito')
			url = reverse('usuario:listar-directivos')

			return HttpResponseRedirect(url)

		user_form = UserForm(request.POST)
		estudiante_form = EstudianteForm(request.POST)
		messages.error(request,'Hay errores en algun campo, revise el formulario')

		context = {
		'section_title':'Crear Usuario Tipo Estudiante',
		'user_form':user_form,
		'estudiante_form': estudiante_form, }

		return render(request, 'usuario/estudiante_form.html', context)


"""UpdateView: Una vista que muestra un formulario para editar un objeto existente, en 
caso de un error retornar el formulario, de lo contrario guarda los cambios. Esto utiliza 
un formulario generado automáticamente a partir de la clase del modelo del objeto """
class DocenteUpdateView(LoginRequiredMixin, TemplateView):
	""" Permite actualizar la información de una persona """


	def get(self, request, *args, **kwargs):
		"""Permite obtener el id y los datos almacenados en la base de datos del usuario
			que se quiere editar"""

		docente = Profesor.objects.get(id=kwargs['epk'])
		user = docente.user
		docente_form = ProfesorForm(instance=docente)
		user_form = UserForm(instance=user)

		context = {
		'section_title':'Actualizar Usuario Tipo Docente',
		'user_form':user_form,
		'docente_form':docente_form }

		return render(request, 'usuario/docente_form.html', context)


	def post(sel, request, *args, **kwargs):
		"""Permite enviar la información modificada del personal a la base de datos, 
		si es valido guarda los datos de lo contrario muestra un mensaje de error y 
		vuelve a cargar el formulario para modificar Personal"""
		
		docente = Profesor.objects.get(id=kwargs['epk'])
		user = docente.user

		docente_form = ProfesorForm(request.POST,request.FILES,instance=docente)
		user_form = UserForm(request.POST,request.FILES,instance=user)

		if user_form.is_valid() and docente_form.is_valid():

			docente.identificacion = directivo_form.cleaned_data['identificacion']
			docente.cargoAdministrativo = directivo_form.cleaned_data['cargoAdministrativo']
			docente.unidadAcademica = directivo_form.cleaned_data['unidadAcademica']
			docente.imagen = directivo_form.cleaned_data['imagen']
			docente.estado = directivo_form.cleaned_data['estado']
			docente.save()

			user.username = user_form.cleaned_data['username']
			user.first_name = user_form.cleaned_data['first_name']
			user.last_name = user_form.cleaned_data['last_name']
			user.email = user_form.cleaned_data['email']

			password1 = user_form.cleaned_data['password1']
			password2 = user_form.cleaned_data['password2']

			if password1 != "" and password2 != "":
				user.set_password(user_form.cleaned_data['password1'])
			user.save()

			""" En caso de que el administrador este modificando su misma cuenta de 
			usuario, es necesario que vuelva a ser logeado con los nuevos datos username
			y password """
			if user.id == request.user.id:
				user = authenticate(username=user.username, password=password1)
				if user is not None:
					if user.is_active:
						login(request,user)

			messages.info(request,'Usuario tipo docente modificado con exito')
			url = reverse('usuario:listar-docentes')

			return HttpResponseRedirect(url)
		else:
			docente_form = ProfesorForm(request.POST,request.FILES)
			user_form = UserForm(instance=user)

			context = {
			'section_title':'Actualizar Personal',
			'user_form':user_form,
			'docente_form':docente_form }

			return render(request, 'usuario/docente_form.html',context)

"""UpdateView: Una vista que muestra un formulario para editar un objeto existente, en 
caso de un error retornar el formulario, de lo contrario guarda los cambios. Esto utiliza 
un formulario generado automáticamente a partir de la clase del modelo del objeto """
class EstudianteUpdateView(LoginRequiredMixin, TemplateView):
	""" Permite actualizar la información de una persona """


	def get(self, request, *args, **kwargs):
		"""Permite obtener el id y los datos almacenados en la base de datos del usuario
			que se quiere editar"""

		estudiante = Estudiante.objects.get(id=kwargs['epk'])
		user = estudiante.user
		estudiante_form = EstudianteForm(instance=estudiante)
		user_form = UserForm(instance=user)

		context = {
		'section_title':'Actualizar Usuario Tipo Estudiante',
		'user_form':user_form,
		'estudiante_form':estudiante_form }

		return render(request, 'usuario/estudiante_form.html', context)


	def post(sel, request, *args, **kwargs):
		"""Permite enviar la información modificada del personal a la base de datos, 
		si es valido guarda los datos de lo contrario muestra un mensaje de error y 
		vuelve a cargar el formulario para modificar Personal"""
		
		estudiante = Estudiante.objects.get(id=kwargs['epk'])
		user = estudiante.user

		estudiante_form = EstudianteForm(request.POST,request.FILES,instance=estudiante)

gestion/usuario/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Profesor, Estudiante
from inicio.mixins import LoginRequiredMixin
from django.shortcuts import render


"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class DocenteListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = Profesor
	context_object_name = 'docentes'
	template_name = 'usuario/docente_list.html'

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla para 
			listar los vehículos especiales"""
		context = super(DocenteListView,self).get_context_data(**kwargs)
		return context

"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class EstudianteListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = Estudiante
	context_object_name = 'estudiantes'
	template_name = 'usuario/estudiante_list.html'

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla para 
			listar los vehículos especiales"""
		context = super(EstudianteListView,self).get_context_data(**kwargs)
		return context

gestion/usuario/templates/usuario/docente_list.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Docentes (Director Programa, Director Escuela y Docentes)</h4>
                        <!--<h6>(Decan@, Vicedecan@ y Administrativos)</h6>-->
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item"><a href="#">Docentes</a></li>
                            <li class="breadcrumb-item active">Listado</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'usuario:crear-docente' %}" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow btn-danger" ><i class="fa fa-plus"></i> Nuevo Docente </a>
                    <br></br>
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title">Docentes</h4>
                        

                        <p class="text-muted font-14 m-b-30">
                           Listado de docentes
                        </p>


                        <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="text-center">Usuario</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Apellidos</th>
                                <th class="text-center">Unidad Académica</th>
                                <th class="text-center">Cargo Administrativo</th>
                                <th class="text-center">Imagen</th>
                                <th class="text-center">Editar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for usuario in docentes %}
                            <tr>
                                <td>{{usuario.user}}</td>
                                <td>{{usuario.user.first_name}}</td>
                                <td>{{usuario.user.last_name}}</td>
                                <td>{{usuario.unidadAcademica}}</td>
                                <td>{{usuario.cargoAdministrativo}}</td>
                                <td>{% if usuario.imagen %}
                                    <img src={{ usuario.imagen.url }} alt="image" class="img-circle" width=50 height=50/>
                                    {% else %}
                                    <img src="{{ MEDIA_URL }}imagenes/persona/imagen_no_disponible.png" alt="image" class="img-circle" width=50 height=50 />
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                <a href="{% url 'usuario:actualizar-docente' usuario.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-address-card"></i>
                                </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}

<script type="text/javascript">
    $(document).ready(function() {
        // Default Datatable
        $('#datatable').DataTable();

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            lengthChange: false,
                        "language":{
                "lengthMenu":"Mostrar _MENU_ registros.",
                "zeroRecords": "Lo sentimos. No se encontraron registros.",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros aún.",
                "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                "search" : "Consultar:",
                "LoadingRecords": "Cargando ...",
                "Processing": "Procesando...",
                "SearchPlaceholder": "Comience a teclear...",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente", 
                }},
            buttons: [
                {extend: 'copy', text:'<i class="fa fa-copy" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Copiar' },
                {extend: 'csv', text:'<i class="fa fa-file-text-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'CSV',},
                {extend: 'excel', text:'<i class="fa fa-file-excel-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Excel', title: 'Peajes'},
                {extend: 'pdf', text:'<i class="fa fa-file-pdf-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'PDF', title: 'Peajes'},

                {extend: 'print', text:'<i class="fa fa-print" style="font-size:20px; color:#FFFFF";></i>', titleAttr: 'Imprimir', title: 'Peajes',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }]
});
        // Key Tables
        $('#key-table').DataTable({
            keys: true
        });

        // Responsive Datatable
        $('#responsive-datatable').DataTable();

        // Multi Selection Datatable
        $('#selection-datatable').DataTable({
            select: {
                style: 'multi'
            }
        });
        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

{% endblock %}

gestion/usuario/templates/usuario/estudiante_list.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Estudiantes</h4>
                        <!--<h6>(Decan@, Vicedecan@ y Administrativos)</h6>-->
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item"><a href="#">Estudiantes</a></li>
                            <li class="breadcrumb-item active">Listado</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'usuario:crear-estudiante' %}" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow btn-danger" ><i class="fa fa-plus"></i> Nuevo Estudiante </a>
                    <br></br>
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title">Estudiantes</h4>
                        

                        <p class="text-muted font-14 m-b-30">
                           Listado de estudiantes
                        </p>


                        <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="text-center">Usuario</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Apellidos</th>
                                <th class="text-center">Programa</th>
                                <th class="text-center">Código</th>
                                <th class="text-center">Imagen</th>
                                <th class="text-center">Editar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for usuario in estudiantes %}
                            <tr>
                                <td>{{usuario.user}}</td>
                                <td>{{usuario.user.first_name}}</td>
                                <td>{{usuario.user.last_name}}</td>
                                <td>{{usuario.programa}}</td>
                                <td>{{usuario.codigo}}</td>
                                <td>{% if usuario.imagen %}
                                    <img src={{ usuario.imagen.url }} alt="image" class="img-circle" width=50 height=50/>
                                    {% else %}
                                    <img src="{{ MEDIA_URL }}imagenes/persona/imagen_no_disponible.png" alt="image" class="img-circle" width=50 height=50 />
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                <a href="{% url 'usuario:actualizar-estudiante' usuario.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-address-card"></i>
                                </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}

<script type="text/javascript">
    $(document).ready(function() {
        // Default Datatable
        $('#datatable').DataTable();

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            lengthChange: false,
                        "language":{
                "lengthMenu":"Mostrar _MENU_ registros.",
                "zeroRecords": "Lo sentimos. No se encontraron registros.",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros aún.",
                "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                "search" : "Consultar:",
                "LoadingRecords": "Cargando ...",
                "Processing": "Procesando...",
                "SearchPlaceholder": "Comience a teclear...",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente", 
                }},
            buttons: [
                {extend: 'copy', text:'<i class="fa fa-copy" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Copiar' },
                {extend: 'csv', text:'<i class="fa fa-file-text-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'CSV',},
                {extend: 'excel', text:'<i class="fa fa-file-excel-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Excel', title: 'Peajes'},
                {extend: 'pdf', text:'<i class="fa fa-file-pdf-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'PDF', title: 'Peajes'},

                {extend: 'print', text:'<i class="fa fa-print" style="font-size:20px; color:#FFFFF";></i>', titleAttr: 'Imprimir', title: 'Peajes',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }]
});
        // Key Tables
        $('#key-table').DataTable({
            keys: true
        });

        // Responsive Datatable
        $('#responsive-datatable').DataTable();

        // Multi Selection Datatable
        $('#selection-datatable').DataTable({
            select: {
                style: 'multi'
            }
        });
        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

{% endblock %}