gestion/curso/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import CursoCreateView, CursoUpdateView, CursoDeleteView, AreaCreateView, AreaUpdateView, AreasInternacionalesCreateView, AreasInternacionalesUpdateView, AreaDeleteView
from .views import CursoListView, AreaListView, AreasInternacionalesListView

app_name = 'curso'

urlpatterns = [

	path('curso/crear/', CursoCreateView.as_view(), name='crear'),
	path('curso/listar/', CursoListView.as_view(), name='listar'),
	path('curso/actualizar/<int:pk>', CursoUpdateView.as_view(), name='actualizar'),
	path('curso/eliminar/<int:pk>', CursoDeleteView.as_view(), name='eliminar'),
	path('curso/creararea/', AreaCreateView.as_view(), name='crearArea'),
	path('curso/listararea/', AreaListView.as_view(), name='listarArea'),
	path('curso/actualizararea/<int:pk>', AreaUpdateView.as_view(), name='actualizarArea'),
	path('curso/eliminararea/<int:pk>', AreaDeleteView.as_view(), name='eliminarArea'),
	path('curso/crearareainternacional/', AreasInternacionalesCreateView.as_view(), name='crearAreaInternacional'),
	path('curso/listarareainternacional/', AreasInternacionalesListView.as_view(), name='listarAreaInternacional'),
	path('curso/actualizarareainternacional/<int:pk>', AreasInternacionalesUpdateView.as_view(), name='actualizarAreaInternacional'),
]

gestion/gestion/urls.py
from django.urls import include, path
from django.contrib import admin
from gestion import settings
from django.views.static import serve
from inicio import views
from django.conf.urls import handler404, handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'inicio.views.pag_404_not_found'
handler500 = 'inicio.views.pag_500_error_server'

gestion/ra/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import RACreateView, RAUpdateView
from .views import RAListView

app_name = 'resultadoaprendizaje'

urlpatterns = [

	path('resultadoaprendizaje/crear/(<int:pk>)', RACreateView.as_view(), name='crear'),
	path('resultadoaprendizaje/listar/', RAListView.as_view(), name='listar'),
	path('resultadoaprendizaje/actualizar/<int:pk>', RAUpdateView.as_view(), name='actualizar'),
]

gestion/curso/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.template import loader
from django.template import Context
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.contrib import messages
from django import forms
from inicio.mixins import LoginRequiredMixin
from .models import Curso, Area, AreasInternacionales
import json

"""FormView: Es una vista que muestra un formulario. En caso de error, vuelve a mostrar el 
formulario con errores de validación; en caso de éxito, redirige a una nueva URL"""
class CursoCreateForm(LoginRequiredMixin, forms.ModelForm):
	"""Permite crear un formulario con los campos del facultad"""

	nombre = forms.CharField(label='Nombre')
	descripcion = forms.Textarea()
	metodologia = forms.Textarea()
	

	def clean_nombre(self):
		"""Permite validar que el campo nombre_propietario sólo contenga letras[A-Z],[a-z]"""

		n=0
		nombre = self.cleaned_data['nombre']
		if nombre.isalpha():
			return nombre
		else:
			if " " in nombre:
				separar=nombre.split(" ")
				for c in range(len(separar)):
					if separar[c].isalpha():
						n=n+1
					else:
						n=-1
						break
				if n>0:
					return nombre
				else:
					if n<0:
						raise forms.ValidationError('El nombre del curso solo puede contener letras')
			else:
				raise forms.ValidationError("El nombre del curso solo puede contener letras")	


	class Meta:
		"""Permite determinar del modelo Facultad y el campo nombre que se muestran en el formulario"""
		model = Curso
		fields = ['nombre', 'codigo', 'area', 'creditos', 'horas', 'horasClase', 'descripcion', 'tipo', 'ciclo', 'escuela', 'metodologia']

"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay errores
	muestra mensajes de error y si no, guarda el objeto"""	
class CursoCreateView(LoginRequiredMixin, CreateView):
	"""Permite mostrar el formulario para crear una facultad"""
	form_class = CursoCreateForm
	model = Curso

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para crear un VehículoEspecial"""
		context = super(CursoCreateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Nuevo Curso'
		context['button_text'] = 'Crear'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El curso ha sido creado con exito")
		return reverse_lazy('curso:listar')

"""UpdateView: Es una vista que muestra un formulario para editar un objeto existente, 
en caso de un error retorna el formulario, de lo contrario guarda los cambios. Esto 
utiliza un formulario generado automáticamente a partir de la clase de modelo del objeto"""
class CursoUpdateView(LoginRequiredMixin, UpdateView):
	"""Permite actualizar la información de una facultad"""

	model = Curso
	fields = ['nombre', 'codigo', 'area', 'creditos','horas', 'horasClase', 'descripcion', 'tipo', 'ciclo', 'escuela']
	success_url = reverse_lazy('curso:listar')

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para actualizar una facultad"""
		context = super(CursoUpdateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Actualizar Curso'
		context['button_text'] = 'Actualizar'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El curso ha sido actualizado con exito")
		return reverse_lazy('curso:listar')

class CursoDeleteView(LoginRequiredMixin, DeleteView):
	"""Permite mientras se ejecuta contener el objeto persona sobre el que se esta 
	operando la vista"""
	
	model = Curso
	template_name = 'curso/curso_confirm_delete.html'
	success_url = reverse_lazy('curso:listar')


"""FormView: Es una vista que muestra un formulario. En caso de error, vuelve a mostrar el 
formulario con errores de validación; en caso de éxito, redirige a una nueva URL"""
class AreaCreateForm(LoginRequiredMixin, forms.ModelForm):
	"""Permite crear un formulario con los campos del facultad"""

	nombre = forms.CharField(label='Nombre')
	

	def clean_nombre(self):
		"""Permite validar que el campo nombre_propietario sólo contenga letras[A-Z],[a-z]"""

		n=0
		nombre = self.cleaned_data['nombre']
		if nombre.isalpha():
			return nombre
		else:
			if " " in nombre:
				separar=nombre.split(" ")
				for c in range(len(separar)):
					if separar[c].isalpha():
						n=n+1
					else:
						n=-1
						break
				if n>0:
					return nombre
				else:
					if n<0:
						raise forms.ValidationError('El nombre de una área solo puede contener letras')
			else:
				raise forms.ValidationError("El nombre de una área solo puede contener letras")	


	class Meta:
		"""Permite determinar del modelo Facultad y el campo nombre que se muestran en el formulario"""
		model = Area
		fields = ['nombre', 'color', 'escuela']

"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay errores
	muestra mensajes de error y si no, guarda el objeto"""	
class AreaCreateView(LoginRequiredMixin, CreateView):
	"""Permite mostrar el formulario para crear una facultad"""
	form_class = AreaCreateForm
	model = Area

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para crear un VehículoEspecial"""
		context = super(AreaCreateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Nuevo Área'
		context['button_text'] = 'Crear'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El área ha sido creada con exito")
		return reverse_lazy('curso:listarArea')

"""UpdateView: Es una vista que muestra un formulario para editar un objeto existente, 
en caso de un error retorna el formulario, de lo contrario guarda los cambios. Esto 
utiliza un formulario generado automáticamente a partir de la clase de modelo del objeto"""
class AreaUpdateView(LoginRequiredMixin, UpdateView):
	"""Permite actualizar la información de una facultad"""

	model = Area
	fields = ['nombre', 'color', 'escuela']
	success_url = reverse_lazy('curso:listarArea')

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para actualizar una facultad"""
		context = super(AreaUpdateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Actualizar Área'
		context['button_text'] = 'Actualizar'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El área ha sido actualizada con exito")
		return reverse_lazy('curso:listarArea')

class AreaDeleteView(LoginRequiredMixin, DeleteView):
	"""Permite mientras se ejecuta contener el objeto persona sobre el que se esta 
	operando la vista"""
	
	model = Area
	template_name = 'curso/area_confirm_delete.html'
	success_url = reverse_lazy('curso:listarArea')

class AreasInternacionalesCreateForm(LoginRequiredMixin, forms.ModelForm):
	"""Permite crear un formulario con los campos del facultad"""

	nombre = forms.CharField(label='Nombre')
	
	class Meta:
		"""Permite determinar del modelo Facultad y el campo nombre que se muestran en el formulario"""
		model = AreasInternacionales
		fields = ['nombre', 'color', 'escuela',]

"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay errores
	muestra mensajes de error y si no, guarda el objeto"""	
class AreasInternacionalesCreateView(LoginRequiredMixin, CreateView):
	"""Permite mostrar el formulario para crear una facultad"""
	form_class = AreasInternacionalesCreateForm
	model = AreasInternacionales

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para crear un VehículoEspecial"""
		context = super(AreasInternacionalesCreateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Nuevo Área Internacional'
		context['button_text'] = 'Crear'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El área internacional ha sido creada con exito")
		return reverse_lazy('curso:listarAreaInternacional')

"""UpdateView: Es una vista que muestra un formulario para editar un objeto existente, 
en caso de un error retorna el formulario, de lo contrario guarda los cambios. Esto 
utiliza un formulario generado automáticamente a partir de la clase de modelo del objeto"""
class AreasInternacionalesUpdateView(LoginRequiredMixin, UpdateView):
	"""Permite actualizar la información de una facultad"""

	model = AreasInternacionales
	fields = ['nombre', 'color', 'escuela']
	success_url = reverse_lazy('curso:listarAreaInternacional')

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para actualizar una facultad"""
		context = super(AreasInternacionalesUpdateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Actualizar Área Internacional'
		context['button_text'] = 'Actualizar'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"El área internacional ha sido actualizada con exito")
		return reverse_lazy('curso:listarAreaInternacional')

gestion/curso/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Curso, Area, AreasInternacionales
from inicio.mixins import LoginRequiredMixin
from django.shortcuts import render


"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class CursoListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = Curso
	context_object_name = 'cursos'
	template_name = 'curso/curso_list.html'

	def get_queryset(self):
		#persona = self.kwargs['pk']
		#unidad = user.unidadacademica
		if self.request.user.profesor.cargoAdministrativo == "Director de Escuela":
			return Curso.objects.filter(escuela=self.request.user.profesor.unidadAcademica)
		elif self.request.user.profesor.cargoAdministrativo == "Director de Programa":
			return Curso.objects.filter(escuela=self.request.user.profesor.unidadAcademica)


"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class AreaListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = Area
	context_object_name = 'areas'
	template_name = 'curso/area_list.html'

	def get_queryset(self):
		return Area.objects.filter(escuela=self.request.user.profesor.unidadAcademica)

"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class AreasInternacionalesListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = AreasInternacionales
	context_object_name = 'areasinternacionales'
	template_name = 'curso/areasinternacionales_list.html'

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla para 
			listar los vehículos especiales"""
		context = super(AreasInternacionalesListView,self).get_context_data(**kwargs)
		return context

gestion/curso/templates/curso/area_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Área</h4>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Área</li>
                    <li class="breadcrumb-item active">{{section_title}}</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">Área</h4>
                    <p class="text-muted m-b-30 font-14">
                        Eliminar Área
                    </p>
                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                <form action="" method="post">{% csrf_token %}
                                    <ul>Esta seguro que desea eliminar el área: {{object}}</ul>
                                    <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                                    <a href="{% url 'curso:listarArea'%}">
                                    <input class="btn btn-primary"  type="button" value="Cancelar"></a>                        
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

gestion/curso/templates/curso/area_form.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        <div class="col-sm-12">
                <div class="page-title-box">
                    <h4 class="page-title">Área</h4>
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">Área</li>
                        <li class="breadcrumb-item active">{{section_title}}</li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">Área</h4>
                    <p class="text-muted m-b-30 font-14">
                        Por favor complete el formulario
                    </p>
                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                <form method="post" class="form-horizontal" role="form">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-lg-6">
                                        {% bootstrap_form form %}
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                                    </div>                        
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'gestion/assets/js/jscolor.js' %}"></script>

{% endblock %}
{% block javascript %}
{{ block.super }}

{% endblock %}

gestion/curso/templates/curso/area_list.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Áreas</h4>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item"><a href="#">Áreas</a></li>
                            <li class="breadcrumb-item active">Listado</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'curso:crearArea' %}" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow btn-danger" ><i class="fa fa-plus"></i> Nueva Área </a>
                    <br></br>
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title">Áreas</h4>
                        <p class="text-muted font-14 m-b-30">
                           Listado de áreas
                        </p>

                        <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Color</th>
                                <th class="text-center">Escuela</th>
                                <th class="text-center">Editar</th>
                                <th class="text-center">Eliminar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for area in areas %}
                            <tr>
                                <td>{{area.nombre}}</td>
                                <td>{{area.color}}</td>
                                <td>{{area.escuela}}</td>
                                <td class="text-center">
                                <a href="{% url 'curso:actualizarArea' area.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-pencil-square-o"></i>
                                </a>
                                </td>
                                <td class="text-center">
                                <a href="{% url 'curso:eliminarArea' area.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-trash" style= "color:#f9473e"></i>
                                </a>
                                </td>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}

<script type="text/javascript">
    $(document).ready(function() {
        // Default Datatable
        $('#datatable').DataTable();

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            lengthChange: false,
                        "language":{
                "lengthMenu":"Mostrar _MENU_ registros.",
                "zeroRecords": "Lo sentimos. No se encontraron registros.",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros aún.",
                "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                "search" : "Consultar:",
                "LoadingRecords": "Cargando ...",
                "Processing": "Procesando...",
                "SearchPlaceholder": "Comience a teclear...",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente", 
                }},
            buttons: [
                {extend: 'copy', text:'<i class="fa fa-copy" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Copiar' },
                {extend: 'csv', text:'<i class="fa fa-file-text-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'CSV',},
                {extend: 'excel', text:'<i class="fa fa-file-excel-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Excel', title: 'Peajes'},
                {extend: 'pdf', text:'<i class="fa fa-file-pdf-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'PDF', title: 'Peajes'},

                {extend: 'print', text:'<i class="fa fa-print" style="font-size:20px; color:#FFFFF";></i>', titleAttr: 'Imprimir', title: 'Peajes',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }]
});
        // Key Tables
        $('#key-table').DataTable({
            keys: true
        });

        // Responsive Datatable
        $('#responsive-datatable').DataTable();

        // Multi Selection Datatable
        $('#selection-datatable').DataTable({
            select: {
                style: 'multi'
            }
        });
        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

{% endblock %}

gestion/curso/templates/curso/curso_list.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Cursos de la Unidad Académica</h4>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item"><a href="#">Cursos de la Unidad Académica</a></li>
                            <li class="breadcrumb-item active">Listado</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'curso:crear' %}" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow btn-danger" ><i class="fa fa-plus"></i> Nuevo Curso </a>
                    <br></br>
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title">Cursos de la Unidad Académica</h4>
                        <p class="text-muted font-14 m-b-30">
                           Listado de cursos
                        </p>

                        <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Código</th>
                                <th class="text-center">Créditos</th>
                                <th class="text-center">Horas</th>
                                <th class="text-center">Horas de trabajo independiente</th>
                                <th class="text-center">Área</th>
                                <th class="text-center">Tipo</th>
                                <th class="text-center">Ciclo</th>
                                <th class="text-center">Editar</th>
                                <th class="text-center">Eliminar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for curso in cursos %}
                            <tr>
                                <td>{{curso.nombre}}</td>
                                <td>{{curso.codigo}}</td>
                                <td>{{curso.creditos}}</td>
                                <td>{{curso.horas}}</td>
                                <td>{{curso.horasClase}}</td>
                                <td>{% for area in curso.area.all %}
                                 * {{area.nombre}}</br>
                                {% endfor %}</td>
                       
                                <td>{{curso.tipo}}</td>
                                <td>{{curso.ciclo}}</td>
                                <td class="text-center">
                                <a href="{% url 'curso:actualizar' curso.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-pencil-square-o"></i>
                                </a>
                                </td>
                                <td class="text-center">
                                <a href="{% url 'curso:eliminar' curso.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-trash" style= "color:#f9473e"></i>
                                </a>
                                </td>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}

<script type="text/javascript">
    $(document).ready(function() {
        // Default Datatable
        $('#datatable').DataTable();

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            lengthChange: false,
                        "language":{
                "lengthMenu":"Mostrar _MENU_ registros.",
                "zeroRecords": "Lo sentimos. No se encontraron registros.",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros aún.",
                "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                "search" : "Consultar:",
                "LoadingRecords": "Cargando ...",
                "Processing": "Procesando...",
                "SearchPlaceholder": "Comience a teclear...",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente", 
                }},
            buttons: [
                {extend: 'copy', text:'<i class="fa fa-copy" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Copiar' },
                {extend: 'csv', text:'<i class="fa fa-file-text-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'CSV',},
                {extend: 'excel', text:'<i class="fa fa-file-excel-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Excel', title: 'Peajes'},
                {extend: 'pdf', text:'<i class="fa fa-file-pdf-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'PDF', title: 'Peajes'},

                {extend: 'print', text:'<i class="fa fa-print" style="font-size:20px; color:#FFFFF";></i>', titleAttr: 'Imprimir', title: 'Peajes',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }]
});
        // Key Tables
        $('#key-table').DataTable({
            keys: true
        });

        // Responsive Datatable
        $('#responsive-datatable').DataTable();

        // Multi Selection Datatable
        $('#selection-datatable').DataTable({
            select: {
                style: 'multi'
            }
        });
        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

{% endblock %}