gestion/gestion/urls.py
from django.urls import include, path
from django.contrib import admin
from gestion import settings
from django.views.static import serve
from inicio import views
from django.conf.urls import handler404, handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'inicio.views.pag_404_not_found'
handler500 = 'inicio.views.pag_500_error_server'

gestion/ra/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import RACreateView, RAUpdateView
from .views import RAListView

app_name = 'resultadoaprendizaje'

urlpatterns = [

	path('resultadoaprendizaje/crear/(<int:pk>)', RACreateView.as_view(), name='crear'),
	path('resultadoaprendizaje/listar/', RAListView.as_view(), name='listar'),
	path('resultadoaprendizaje/actualizar/<int:pk>', RAUpdateView.as_view(), name='actualizar'),
]

gestion/unidadacademica/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import UnidadAcademicaCreateView, UnidadAcademicaUpdateView, UnidadAcademicaDeleteView
from .views import UnidadAcademicaListView

app_name = 'unidadacademica'

urlpatterns = [

	path('unidadacademica/crear/', UnidadAcademicaCreateView.as_view(), name='crear'),
	path('unidadacademica/listar/', UnidadAcademicaListView.as_view(), name='listar'),
	path('unidadacademica/actualizar/<int:pk>', UnidadAcademicaUpdateView.as_view(), name='actualizar'),
	path('unidadacademica/eliminar/<int:pk>', UnidadAcademicaDeleteView.as_view(), name='eliminar'),
]

gestion/unidadacademica/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from facultad.models import Facultad

#Django por defecto, cuando los modelos no tienen primary_key, coloca una llamada "id"
"""Model: Define la estructura de la tabla UnidadAcademica en base de datos"""
class UnidadAcademica(models.Model):
	"""Permite definir un listado de UnidadesAcademicas"""

	#Nombre de la unidad academica
	nombre = models.CharField(max_length=200)
	#Facultad a la que pertenece
	facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)


	"""Permite ordenar la lista de unidades academicas por nombre y asignarle el nombre en 
	plural"""
	class Meta:
		ordering = ['nombre']
		verbose_name_plural = "Unidades Academicas"

	#Permite determinar una representación en string del objeto Unidad Academica
	def __str__(self):
		return self.nombre

	"""Permite determinar una representación en string para el objeto Unidad Academica (Para 
	versiones de Python 2)"""
	def __unicode__(self):
		return self.nombre

gestion/unidadacademica/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.template import loader
from django.template import Context
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.contrib import messages
from django import forms
from inicio.mixins import LoginRequiredMixin
from .models import UnidadAcademica
import json

"""FormView: Es una vista que muestra un formulario. En caso de error, vuelve a mostrar el 
formulario con errores de validación; en caso de éxito, redirige a una nueva URL"""
class UnidadAcademicaCreateForm(LoginRequiredMixin, forms.ModelForm):
	"""Permite crear un formulario con los campos del facultad"""

	nombre = forms.CharField(label='Nombre')
	

	def clean_nombre(self):
		"""Permite validar que el campo nombre_propietario sólo contenga letras[A-Z],[a-z]"""

		n=0
		nombre = self.cleaned_data['nombre']
		if nombre.isalpha():
			return nombre
		else:
			if " " in nombre:
				separar=nombre.split(" ")
				for c in range(len(separar)):
					if separar[c].isalpha():
						n=n+1
					else:
						n=-1
						break
				if n>0:
					return nombre
				else:
					if n<0:
						raise forms.ValidationError('El nombre de la unidad académica solo puede contener letras')
			else:
				raise forms.ValidationError("El nombre de la unidad académica solo puede contener letras")	


	class Meta:
		"""Permite determinar del modelo Facultad y el campo nombre que se muestran en el formulario"""
		model = UnidadAcademica
		fields = ['nombre', 'facultad']

"""CreateView: Es una vista que muestra un formulario para crear un objeto. Si hay errores
	muestra mensajes de error y si no, guarda el objeto"""	
class UnidadAcademicaCreateView(LoginRequiredMixin, CreateView):
	"""Permite mostrar el formulario para crear una facultad"""
	form_class = UnidadAcademicaCreateForm
	model = UnidadAcademica

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para crear un VehículoEspecial"""
		context = super(UnidadAcademicaCreateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Nueva Unidad Académica'
		context['button_text'] = 'Crear'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"La unidad académica ha sido creada con exito")
		return reverse_lazy('unidadacademica:listar')

"""UpdateView: Es una vista que muestra un formulario para editar un objeto existente, 
en caso de un error retorna el formulario, de lo contrario guarda los cambios. Esto 
utiliza un formulario generado automáticamente a partir de la clase de modelo del objeto"""
class UnidadAcademicaUpdateView(LoginRequiredMixin, UpdateView):
	"""Permite actualizar la información de una facultad"""

	model = UnidadAcademica
	fields = ['nombre', 'facultad']
	success_url = reverse_lazy('unidadacademica:listar')

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla 
		para actualizar una facultad"""
		context = super(UnidadAcademicaUpdateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Actualizar Unidad Académica'
		context['button_text'] = 'Actualizar'
		return context

	def get_success_url(self):
		"""Permite mostrar un mensaje de confirmación y redirecciona al listado de 
		VehiculoEspecial"""
		messages.info(self.request,"La unidad académica ha sido actualizada con exito")
		return reverse_lazy('unidadacademica:listar')

class UnidadAcademicaDeleteView(LoginRequiredMixin, DeleteView):
	"""Permite mientras se ejecuta contener el objeto persona sobre el que se esta 
	operando la vista"""
	
	model = UnidadAcademica
	template_name = 'unidadacademica/unidadacademica_confirm_delete.html'
	success_url = reverse_lazy('unidadacademica:listar')

gestion/unidadacademica/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import UnidadAcademica
from inicio.mixins import LoginRequiredMixin
from django.shortcuts import render


"""ListView: Es una vista que permite mostrar un listado de cualquier objeto existente"""
class UnidadAcademicaListView(LoginRequiredMixin, ListView):
	"""Permite listar todos los vehículos especiales de la base de datos"""

	model = UnidadAcademica
	context_object_name = 'unidadesacademicas'
	template_name = 'unidadacademica/unidadacademica_list.html'

	def get_context_data(self,**kwargs):
		"""Permite devolver un diccionario que representa el contexto de la plantilla para 
			listar los vehículos especiales"""
		context = super(UnidadAcademicaListView,self).get_context_data(**kwargs)
		return context

gestion/unidadacademica/templates/unidadacademica/unidadacademica_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Unidad Académica</h4>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Unidad Académica</li>
                    <li class="breadcrumb-item active">{{section_title}}</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">Unidad Académica</h4>
                    <p class="text-muted m-b-30 font-14">
                        Eliminar Unidad Académica
                    </p>
                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                <form action="" method="post">{% csrf_token %}
                                    <ul>Esta seguro que desea eliminar la unidad académica: {{object}}</ul>
                                    <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                                    <a href="{% url 'unidadacademica:listar'%}">
                                    <input class="btn btn-primary"  type="button" value="Cancelar"></a>                        
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

gestion/unidadacademica/templates/unidadacademica/unidadacademica_form.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        <div class="col-sm-12">
                <div class="page-title-box">
                    <h4 class="page-title">Unidad Académica</h4>
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">Unidad Académica</li>
                        <li class="breadcrumb-item active">{{section_title}}</li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">Unidad Académica</h4>
                    <p class="text-muted m-b-30 font-14">
                        Por favor complete el formulario
                    </p>
                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                <form method="post" class="form-horizontal" role="form">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-lg-6">
                                        {% bootstrap_form form %}
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                                    </div>                        
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
{{ block.super }}

{% endblock %}

gestion/unidadacademica/templates/unidadacademica/unidadacademica_list.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Unidades Académicas</h4>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item"><a href="#">Unidades Académicas</a></li>
                            <li class="breadcrumb-item active">Listado</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title">Unidades Académicas</h4>
                        <p class="text-muted font-14 m-b-30">
                           Listado de unidades académicas
                        </p>

                        <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Facultad</th>
                                <th class="text-center">Editar</th>
                                <th class="text-center">Eliminar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for unidadcademica in unidadesacademicas %}
                            <tr>
                                <td>{{unidadcademica.nombre}}</td>
                                <td>{{unidadcademica.facultad}}</td>
                                <td class="text-center">
                                <a href="{% url 'unidadacademica:actualizar' unidadcademica.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-pencil-square-o"></i>
                                </a>
                                </td>
                                <td class="text-center">
                                <a href="{% url 'unidadacademica:eliminar' unidadcademica.id %}" class="btn btn-white btn-bitbucket"><i class="fa fa-trash" style= "color:#f9473e"></i>
                                </a>
                                </td>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}

<script type="text/javascript">
    $(document).ready(function() {
        // Default Datatable
        $('#datatable').DataTable();

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            lengthChange: false,
                        "language":{
                "lengthMenu":"Mostrar _MENU_ registros.",
                "zeroRecords": "Lo sentimos. No se encontraron registros.",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros aún.",
                "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                "search" : "Consultar:",
                "LoadingRecords": "Cargando ...",
                "Processing": "Procesando...",
                "SearchPlaceholder": "Comience a teclear...",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente", 
                }},
            buttons: [
                {extend: 'copy', text:'<i class="fa fa-copy" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Copiar' },
                {extend: 'csv', text:'<i class="fa fa-file-text-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'CSV',},
                {extend: 'excel', text:'<i class="fa fa-file-excel-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'Excel', title: 'Peajes'},
                {extend: 'pdf', text:'<i class="fa fa-file-pdf-o" style="font-size:20px; color:#FFFFFF;"></i>', titleAttr: 'PDF', title: 'Peajes'},

                {extend: 'print', text:'<i class="fa fa-print" style="font-size:20px; color:#FFFFF";></i>', titleAttr: 'Imprimir', title: 'Peajes',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }]
});
        // Key Tables
        $('#key-table').DataTable({
            keys: true
        });

        // Responsive Datatable
        $('#responsive-datatable').DataTable();

        // Multi Selection Datatable
        $('#selection-datatable').DataTable({
            select: {
                style: 'multi'
            }
        });
        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );
</script>

{% endblock %}