gestion/curso/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import CursoCreateView, CursoUpdateView, CursoDeleteView, AreaCreateView, AreaUpdateView, AreasInternacionalesCreateView, AreasInternacionalesUpdateView, AreaDeleteView
from .views import CursoListView, AreaListView, AreasInternacionalesListView

app_name = 'curso'

urlpatterns = [

	path('curso/crear/', CursoCreateView.as_view(), name='crear'),
	path('curso/listar/', CursoListView.as_view(), name='listar'),
	path('curso/actualizar/<int:pk>', CursoUpdateView.as_view(), name='actualizar'),
	path('curso/eliminar/<int:pk>', CursoDeleteView.as_view(), name='eliminar'),
	path('curso/creararea/', AreaCreateView.as_view(), name='crearArea'),
	path('curso/listararea/', AreaListView.as_view(), name='listarArea'),
	path('curso/actualizararea/<int:pk>', AreaUpdateView.as_view(), name='actualizarArea'),
	path('curso/eliminararea/<int:pk>', AreaDeleteView.as_view(), name='eliminarArea'),
	path('curso/crearareainternacional/', AreasInternacionalesCreateView.as_view(), name='crearAreaInternacional'),
	path('curso/listarareainternacional/', AreasInternacionalesListView.as_view(), name='listarAreaInternacional'),
	path('curso/actualizarareainternacional/<int:pk>', AreasInternacionalesUpdateView.as_view(), name='actualizarAreaInternacional'),
]

gestion/gestion/urls.py
from django.urls import include, path
from django.contrib import admin
from gestion import settings
from django.views.static import serve
from inicio import views
from django.conf.urls import handler404, handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'inicio.views.pag_404_not_found'
handler500 = 'inicio.views.pag_500_error_server'

gestion/inicio/urls.py
# -*- encoding: utf-8 -*-

from django.urls import path
from django.contrib import admin
from .views import Login, Logout, Iniciar


app_name = 'inicio'


urlpatterns = [

	#Para el inicio y cierre de sesion
	path('', Iniciar.as_view(), name='inicio'),
	#path('', Login.as_view(), name='login'),
	path('inicio/login/', Login.as_view(), name='login'),
	path('inicio/logout/', Logout.as_view(), name='logout'),
]

gestion/perfil/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import PerfilCreateView, PerfilUpdateView, PerfilDeleteView, ProgramaEducativoCreateView, ProgramaEducativoUpdateView, ProgramaEducativoDeleteView
from .views import PerfilListView, AmbitosListView, PdfPerfilCreateView, ProgramaEducativoListView

app_name = 'perfil'

urlpatterns = [

	path('perfil/crear/', PerfilCreateView.as_view(), name='crear'),
	path('perfil/listar/', PerfilListView.as_view(), name='listar'),
	path('perfil/listar/ambitos', AmbitosListView.as_view(), name='listar-ambitos'),
	path('perfil/actualizar/<int:pk>', PerfilUpdateView.as_view(), name='actualizar'),
	path('perfil/eliminar/<int:pk>', PerfilDeleteView.as_view(), name='eliminar'),
	path('perfil/PDF/(<int:pk>)', PdfPerfilCreateView.as_view(), name='perfilpdf'),
	path('perfil/programaeducativo/crear', ProgramaEducativoCreateView.as_view(), name='crearpep'),
	path('perfil/programaeducativo/listar/', ProgramaEducativoListView.as_view(), name='listarpep'),
	path('perfil/programaeducativo/actualizar/<int:pk>', ProgramaEducativoUpdateView.as_view(), name='actualizarpep'),
	path('perfil/programaeducativo/eliminar/<int:pk>', ProgramaEducativoDeleteView.as_view(), name='eliminarpep'),

]

gestion/ra/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import RACreateView, RAUpdateView
from .views import RAListView

app_name = 'resultadoaprendizaje'

urlpatterns = [

	path('resultadoaprendizaje/crear/(<int:pk>)', RACreateView.as_view(), name='crear'),
	path('resultadoaprendizaje/listar/', RAListView.as_view(), name='listar'),
	path('resultadoaprendizaje/actualizar/<int:pk>', RAUpdateView.as_view(), name='actualizar'),
]

gestion/scc/urls.py
 # -*- coding: utf-8 -*-
from django.urls import path
from . import views
from .forms import MesoCreateView

app_name = 'facultad'

urlpatterns = [

	path('meso/crear/', MesoCreateView.as_view(), name='crear'),
	#path('scc/listar/', FacultadListView.as_view(), name='listar'),
]

gestion/templates/includes/css.html
{% load staticfiles %}

<link rel="shortcut icon" href="{% static 'minton/Landing/images/favicon.ico' %}">
<link href="{% static 'minton/Admin/material/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'minton/Admin/material/assets/css/icons.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'minton/Admin/material/assets/css/style.css' %}" rel="stylesheet" type="text/css">

<link href="{% static 'minton/Admin/plugins/switchery/switchery.min.css' %}" rel="stylesheet" />
<link rel="stylesheet"  href="{% static 'minton/Admin/plugins/morris/morris.css' %}" >

<!-- DataTables -->
<link href="{% static 'minton/Admin/plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'minton/Admin/plugins/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<!-- Responsive datatable examples -->
<link href="{% static 'minton/Admin/plugins/datatables/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

<!-- Multi Item Selection examples -->
<link href="{% static 'minton/Admin/plugins/datatables/select.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

<!--Form Wizard-->
<link href="{% static 'minton/Admin/plugins/jquery.steps/css/jquery.steps.css' %}" rel="stylesheet" type="text/css" />

<link href="{% static 'minton/Admin/plugins/summernote/summernote-bs4.css' %}" rel="stylesheet" />

<link href="{% static 'minton/Admin/plugins/fullcalendar/css/fullcalendar.min.css' %}" rel="stylesheet" />

gestion/templates/includes/cssInicio.html
{% load staticfiles %}

<link rel="shortcut icon" href="{% static 'minton/Landing/images/favicon.ico' %}">

<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>

<!-- Bootstrap core CSS -->
<link href="{% static 'minton/Landing/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Animate -->
<link href="{% static 'minton/Landing/css/animate.css' %}" rel="stylesheet">

<!-- Icon-font -->
<link rel="stylesheet" type="text/css" href="{% static 'minton/Landing/css/themify-icons.css' %}">

<!-- Custom styles for this template -->
<link href="{% static 'minton/Landing/css/style.css' %}" rel="stylesheet">

gestion/templates/includes/form.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% bootstrap_form form %}

gestion/templates/includes/javascript.html
{% load staticfiles %}

<script>
    var resizefunc = [];
</script>

<!-- Plugins  -->
<script src="{% static 'minton/Admin/material/assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/popper.min.js' %}"></script><!-- Popper for Bootstrap -->
<script src="{% static 'minton/Admin/material/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/detect.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/fastclick.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.blockUI.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/waves.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/wow.min.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/switchery/switchery.min.js' %}"></script>

<!-- Counter Up  -->
<script src="{% static 'minton/Admin/plugins/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/counterup/jquery.counterup.min.js' %}"></script>

<!--Morris Chart-->

<script src="{% static 'minton/Admin/plugins/morris/morris.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/morris/morris.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/raphael/raphael-min.js' %}"></script>

<!-- Page js  -->
<script src="{% static 'minton/Admin/material/assets/pages/jquery.dashboard.js' %}"></script>

<!-- Custom main Js -->
<script src="{% static 'minton/Admin/material/assets/js/jquery.core.js' %}"></script>
<script src="{% static 'minton/Admin/material/assets/js/jquery.app.js' %}"></script>

<!-- Required datatable js -->
<script src="{% static 'minton/Admin/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Buttons examples -->
<script src="{% static 'minton/Admin/plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/buttons.print.min.js' %}"></script>
<!--form summernote-->
<script src="{% static 'minton/Admin/plugins/summernote/summernote-bs4.min.js' %}"></script>
<script>
            jQuery(document).ready(function(){

                $('.summernote').summernote({
                    height: 350,                 // set editor height
                    minHeight: null,             // set minimum height of editor
                    maxHeight: null,             // set maximum height of editor
                    focus: false                 // set focus to editable area after initializing summernote
                });

                $('.inline-editor').summernote({
                    airMode: true
                });

            });
        </script>

<script>
    var resizefunc = [];
</script>




<!-- Examples -->
<script src="{% static 'minton/Admin/plugins/magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/tiny-editable/mindmup-editabletable.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/tiny-editable/numeric-input-example.js' %}"></script>

<script src="{% static 'minton/Admin/material/assets/pages/datatables.editable.init.js' %}"></script>


<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.counter').counterUp({
            delay: 100,
            time: 1200
        });
    });
</script>



<script type="text/javascript">
$(document).ready(function() {
$.extend(jQuery.validator.messages, {
    required: "El Campo es Obligatorio",
    remote: "Por Favor, Rellena este Campo.",
    email: "Por Favor, Escribe una Dirección de Correo Válida",
    url: "Por favor, escribe una URL válida.",
    date: "Por favor, escribe una fecha válida.",
    dateISO: "Por favor, escribe una fecha (ISO) válida.",
    number: "Por favor, escribe un número entero válido.",
    digits: "Por favor, escribe sólo dígitos.",
    creditcard: "Por favor, escribe un número de tarjeta válido.",
    equalTo: "Por favor, escribe el mismo valor de nuevo.",
    accept: "Por favor, escribe un valor con una extensión aceptada.",
    maxlength: jQuery.validator.format("Por favor, no escribas más de {0} caracteres."),
    minlength: jQuery.validator.format("Por favor, no escribas menos de {0} caracteres."),
    rangelength: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
    range: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1}."),
    max: jQuery.validator.format("Por favor, escribe un valor menor o igual a {0}."),
    min: jQuery.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
});
});
</script>
<script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
<script src="{% static 'smart-selects/admin/js/chainedm2m.js' %}"></script>


<script type="text/javascript">
    (function($) {
        var chainfield = "#id_malla";
        var url = "/chaining//filter/curso/Curso/Cursosdelamalla/mallacurricular/CursosMalla/curso";
        var id = "#id_curso";
        var value = undefined;
        var auto_choose = true;
        var empty_label = "-----------";

        $(document).ready(function() {
            chainedm2m.init(chainfield, url, id, value, empty_label, auto_choose);
        });
    })(jQuery || django.jQuery);
    </script>
<!--<script src="{% static 'minton/Admin/plugins/fullcalendar/js/fullcalendar.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'minton/Admin/plugins/select2/select2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'minton/Admin/plugins/moment/moment.js' %}"></script>

<script src="{% static 'minton/Admin/assets/pages/jquery.fullcalendar.js' %}"></script>-->

gestion/templates/includes/menu_administrador.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-bag"></i> <span> Facultad </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'facultad:crear' %}">Crear</a></li>
        <li><a href="{% url 'facultad:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-user"></i> <span> Usuarios </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'usuario:listar-docentes' %}">Docentes</a></li>
        <li><a href="{% url 'usuario:listar-estudiantes' %}">Estudiantes</a></li>
    </ul>
</li>

gestion/templates/includes/menu_director_escuela.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-id-badge"></i> <span> Perfil Egresado </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'perfil:crear' %}">Crear</a></li>
        <li><a href="{% url 'perfil:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-clipboard"></i> <span> Semestre </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'semestre:crear' %}">Crear</a></li>
        <li><a href="{% url 'semestre:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-layout-tab"></i> <span> Gestión de Cursos </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'curso:listarArea' %}">Áreas</a></li>
        <!--<li><a href="{% url 'curso:listarAreaInternacional' %}">Áreas Internacionales</a></li>-->
        <li><a href="{% url 'curso:listar' %}">Cursos</a></li>

    </ul>
</li>

gestion/templates/includes/menu_director_programa.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-id-badge"></i> <span> Perfil Egresado </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'perfil:listar' %}">Ver</a></li>
    </ul>
</li>

<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-book"></i> <span> Proyecto Educativo del Programa </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'perfil:crearpep' %}">Crear</a></li>
        <li><a href="{% url 'perfil:listarpep' %}">Editar/Listar</a></li>
    </ul>
</li>

<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-layout-accordion-list"></i> <span> Malla Curricular </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'mallacurricular:listarPro' %}">Crear</a></li>
        <li><a href="{% url 'mallacurricular:listar' %}">Editar/Listar</a></li>
    </ul>
</li>

<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-check-box"></i> <span> Tributación </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'matriztributacion:listarTributacion' %}">Crear</a></li>

    </ul>
</li>

<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-layout-grid2-thumb"></i> 
        <span> Matriz de tributación </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'matriztributacion:listarTributacionSCC' %}">Cursos/SCC</a></li>
        <!--<li><a href="{% url 'matriztributacion:listarTributacionRA' %}">Cursos/RA</a></li>-->
    </ul>
</li>

<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-list"></i> 
        <span> Diseño de Cursos </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'diseñocurso:crear' %}">Asignar Diseños</a></li>
        <li><a href="{% url 'diseñocurso:listar' %}">Editar/Listar Diseños</a></li> 
    </ul>
</li>

gestion/templates/includes/menu_docente.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-list"></i> 
        <span> Resultado de Aprendizaje </span>
            <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'ra:listar' %}">Crear</a></li>
        <li><a href="{% url 'ra:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-list"></i> 
        <span> Diseño de Cursos </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'diseñocurso:listar' %}">Editar/Listar Diseños</a></li> 
        <li><a href="{% url 'indicadorlogro:crear' %}">Crear IL</a></li>
        <li><a href="{% url 'indicadorlogro:listar' %}">Editar/Listar IL</a></li>
    </ul>
</li>
<!--<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-paint-bucket"></i> <span> Actividad de Aprendizaje </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'actividadaprendizaje:crear' %}">Crear</a></li>
        <li><a href="{% url 'actividadaprendizaje:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-paint-bucket"></i> <span> Actividad de Evaluación </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'actividadevaluativa:crear' %}">Crear</a></li>
        <li><a href="{% url 'actividadevaluativa:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-paint-bucket"></i> <span> Notas </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="ui-buttons.html">Crear</a></li>
        <li><a href="ui-cards.html">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-check-box"></i> 
        <span> Evaluación </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'mallacurricular:listarCursos' %}">Editar/Listar</a></li> 
    </ul>
</li>-->

gestion/templates/includes/menu_estudiante.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-paint-bucket"></i> <span> Cursos </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="ui-buttons.html">Crear</a></li>
        <li><a href="ui-cards.html">Editar/Listar</a></li>
    </ul>
</li>

gestion/templates/includes/menu_facultad.html
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-layers"></i> <span> Unidad Académica </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'unidadacademica:crear' %}">Crear</a></li>
        <li><a href="{% url 'unidadacademica:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-layers-alt"></i> <span> Programa Académico</span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'programa:crear' %}">Crear</a></li>
        <li><a href="{% url 'programa:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-view-list"></i> <span> SCC Facultad </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'sccfacultad:crear' %}">Crear</a></li>
        <li><a href="{% url 'sccfacultad:listar' %}">Editar/Listar</a></li>
    </ul>
</li>
<!--<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-view-list-alt"></i> <span> Componente Facultad </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'componentefacultad:crear' %}">Crear</a></li>
        <li><a href="{% url 'componentefacultad:listar' %}">Editar/Listar</a></li>
    </ul>
</li>-->
<li class="has_sub">
    <a href="javascript:void(0);" class="waves-effect waves-primary"><i class="ti-view-list-alt"></i> <span> Gestión Cursos </span>
        <span class="menu-arrow"></span></a>
    <ul class="list-unstyled">
        <li><a href="{% url 'facultad:listarciclo' %}">Ciclos</a></li>
        <li><a href="{% url 'facultad:listartipoasignatura' %}">Asignaturas</a></li>
        <li><a href="{% url 'facultad:listarformacion' %}">Formación General</a></li>
        <li><a href="{% url 'facultad:listarnivelaprendizaje' %}">Nivel de Aprendizaje</a></li>
    </ul>
</li>

gestion/templates/includes/notificacion_modal.html
{% for message in messages %}
	{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
	<a class="btn btn-info waves-effect waves-light" href="javascript:;" onclick="$.Notification.notify('info','right middle', {{message }} )">Información!</a>
	{% endif %}
	{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
	<a class="btn btn-info waves-effect waves-light" href="javascript:;" onclick="$.Notification.notify('info','right middle', {{message }} )">Información!</a>
	{% endif %}
	{% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
	<a class="btn btn-info waves-effect waves-light" href="javascript:;" onclick="$.Notification.notify('info','right middle', {{message }} )">Información!</a>
	{% endif %}
	{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
	<a class="btn btn-info waves-effect waves-light" href="javascript:;" onclick="$.Notification.notify('info','right middle', {{message }} )">Información!</a>
	{% endif %}
{% endfor %}

gestion/templates/includes/sidebar.html
 <!-- LOGO -->
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Menú</li>

                <li>
                    <a href="{% url 'inicio:logout' %}" class="waves-effect waves-primary"><i
                            class="ti-home"></i><span> Principal </span></a>
                </li>
                {% if user.profesor.cargoAdministrativo == "Administrativo" %}
                    {% include "includes/menu_administrador.html" %}
                {% elif  user.profesor.cargoAdministrativo == "Vicedecano"%}
                    {% include "includes/menu_facultad.html" %}
                {% elif  user.profesor.cargoAdministrativo == "Director de Escuela"%}
                    {% include "includes/menu_director_escuela.html" %}
                {% elif  user.profesor.cargoAdministrativo == "Director de Programa"%}
                    {% include "includes/menu_director_programa.html" %}
                {% elif user.profesor.cargoAdministrativo == "Ninguno"%}
                    {% include "includes/menu_docente.html" %}
                {% else %}
                    {% include "includes/menu_estudiante.html" %}
                {% endif %}


            </ul>

            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>